### ISSUE TITLE
Broken image URLs

### ISSUE THREAD

**Issue by royalicing** [jfhinchcliffe/jfhinchcliffe.github.io#1]
Fav icons should have absolute path (broken on `/projects` page)

```
  <link rel="icon" type="image/png" href="favicon-32x32.png" sizes="32x32" />
  <link rel="icon" type="image/png" href="favicon-16x16.png" sizes="16x16" />
```

Also there is still a lingering `/favicon.ico`, ideally the 16x16 png would be converted to an `.ico` and live at `/favicon.ico`

No file here for the `og:image`: `https://jfhinchcliffe.github.io/images/mugshot.gif`

I _think_ robots.txt should have a url to the sitemap: https://jfhinchcliffe.github.io/robots.txt

**Comment by jfhinchcliffe** [comment]
Fixed! 
Thanks man.
